{
 "title": "Currency API",
 "description": "Dashboard for monitoring the Currency API service metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Convert calls (1m)",
   "type": "timeseries",
   "description": "Number of calls to 'convert' endpoint inside an interval of a minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"controller_convert_timer\" and r._field == \"count\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Failed convert calls (1m)",
   "type": "barchart",
   "description": "Number of failed calls to 'convert' endpoint inside an interval of a minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"controller_convert_fail_counter\" and r._field == \"value\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Convert call response time (1m)",
   "type": "timeseries",
   "description": "Average (mean) and maximum (upper) time taken in milliseconds to process calls to 'convert' endpoint inside an interval of a minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket:\"metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"controller_convert_timer\" and (r._field == \"mean\" or r._field == \"upper\"))\r\n  |> yield()"
    }
   ]
  }
 ]
}