# Spring application parameters
spring:
  application:
    name: currency-api
logging:
  level:
    mhjohans.currency_api.service: DEBUG
# Security parameters
security:
  api_key: 46f4a918-fe60-4564-80a3-fd59caa9816b
# Currency rates API parameters
currency_rates_api:
  key: ${SWOP_API_KEY}
  base_url: https://swop.cx/rest
  # Cache expiry parameters
  supported_currencies:
    cache_ttl: P1D # 1 day
    fallback:  USD, EUR, GBP, JPY, AUD, CAD, CHF, CNY
  currency_rates:
    cache_ttl: PT1M # 1 minute
