# Spring application parameters
spring:
  application:
    name: currency-api
logging:
  level:
    mhjohans.currency_api.service: DEBUG

# Observability parameters
management:
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: WHEN_AUTHORIZED
  influx:
    metrics:
      export:
          org: ${spring.application.name}
          bucket: metrics
          token: ${INFLUX_TOKEN}
          uri: http://${INFLUX_HOST}:8086

# Security parameters
security:
  api-key: 46f4a918-fe60-4564-80a3-fd59caa9816b

# External currency rates API parameters
currency-rates-api:
  key: ${SWOP_API_KEY}
  base-url: https://swop.cx/rest
  # Cache expiry parameters
  supported-currencies:
    cache-ttl: P1D # 1 day
    fallback:  USD, EUR, GBP, JPY, AUD, CAD, CHF, CNY
  currency-rates:
    cache-ttl: PT1M # 1 minute
