apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    isDefault: true
    editable: false
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: currency-api
      defaultBucket: metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
